name: PR Specific Action

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Get PR Name
      id: get_pr_name
      run: |
        PR_NAME=$(jq --raw-output '.pull_request.title' "$GITHUB_EVENT_PATH")
        echo "::set-output name=PR_NAME::$PR_NAME"
    
    - name: Run PR Specific Action
      if: steps.get_pr_name.outputs.PR_NAME == 'My Special PR'
      run: |
        # Add your custom action steps here
        echo "This action will only run for the pull request with title 'My Special PR'"
