name: Update Score

on:
  push:
    branches:
      - main

jobs:

  update-score:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Read Score
      id: read_score
      run: |
        score=$(cat file.txt)
        echo "::set-output name=current_score::$score"
    
    - name: Calculate New Score
      id: calculate_score
      run: |
        new_score=$((${steps.read_score.outputs.current_score} + 5))
        echo "::set-output name=new_score::$new_score"
    
    - name: Append to Score
      run: |
        echo "${{ steps.calculate_score.outputs.new_score }}" >> file.txt
    
    - name: Commit Changes
      uses: stefanzweiler/git-auto-commit-action@v4
      with:
        commit_message: Update file.txt
